[package]
name = "proxmox-client"
version = "0.9.2"
edition = "2024"
description = "Rust client library for the Proxmox VE API"
license = "MIT"
keywords = ["proxmox", "api", "network"]
categories = ["api-bindings", "network-programming"]
repository = "https://github.com/landrzejewski/proxmox-client-rust"
readme = "README.md"


[dependencies]
reqwest = { version = "0.13.2", features = ["json", "cookies"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
urlencoding = "2.1.3"

[dev-dependencies]
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
